SKILL_CATALOG = frozenset({
    "python", "java", "javascript", "typescript", "c#", "c++", "go", "golang",
    "rust", "kotlin", "swift", "php", "ruby", "scala", "r", "matlab", "sql",
    "html", "css", "sass", "less",
    "fastapi", "django", "flask", "tornado", "celery", "pytest", "pandas",
    "numpy", "scipy", "scikit-learn", "sklearn", "pytorch", "tensorflow",
    "keras", "opencv", "nltk", "spacy", "huggingface", "langchain",
    "react", "next.js", "nextjs", "vue", "angular", "svelte", "node.js",
    "nodejs", "express", "nest.js", "nestjs", "redux", "graphql", "apollo",
    "jquery", "webpack", "vite", "tailwind",
    "spring", "spring boot", "hibernate", ".net", "asp.net", "entity framework",
    "laravel", "rails", "symfony",
    "postgresql", "postgres", "mysql", "mariadb", "sqlite", "mongodb",
    "redis", "elasticsearch", "opensearch", "cassandra", "dynamodb",
    "oracle", "sql server", "snowflake", "bigquery", "redshift",
    "aws", "azure", "gcp", "google cloud", "docker", "kubernetes", "k8s",
    "terraform", "ansible", "jenkins", "github actions", "gitlab ci",
    "ci/cd", "linux", "bash", "nginx", "apache", "helm", "prometheus",
    "grafana", "datadog", "sentry",
    "rest", "grpc", "microservices", "event-driven", "kafka", "rabbitmq",
    "sqs", "pubsub", "websocket", "oauth", "jwt", "keycloak", "oidc",
    "linux", "git", "agile", "scrum", "jira", "figma",
    "machine learning", "deep learning", "nlp", "computer vision",
    "data science", "data engineering", "etl", "airflow", "dbt", "spark",
    "hadoop", "databricks", "power bi", "tableau", "looker",
    "selenium", "playwright", "cypress", "junit", "mockito",
    "android", "ios", "react native", "flutter",
    "security", "penetration testing", "owasp", "sast", "dast",
    "product management", "project management", "stakeholder",
    "communication", "leadership", "mentoring",
    "english", "german", "french", "spanish", "persian", "farsi", "arabic",
    "salesforce", "sap", "erp", "crm",
    "html5", "css3", "bootstrap", "material ui", "storybook",
    "prisma", "typeorm", "sqlalchemy", "alembic", "pydantic",
    "uvicorn", "gunicorn", "rabbitmq", "celery",
    "s3", "ec2", "lambda", "rds", "cloudformation", "iam",
    "prometheus", "elk", "splunk",
    "unit testing", "tdd", "bdd", "clean architecture", "ddd",
    "soap", "xml", "json", "yaml", "protobuf",
    "hadoop", "hive", "presto", "trino",
    "mlops", "llm", "openai", "rag", "vector database", "pinecone",
    "weaviate", "chromadb", "faiss",
})

TITLE_HINTS = (
    "engineer", "developer", "programmer", "architect", "scientist",
    "analyst", "manager", "lead", "director", "consultant", "specialist",
    "administrator", "designer", "researcher", "intern", "founder",
    "cto", "cfo", "ceo", "head of", "principal", "staff", "senior",
    "junior", "fullstack", "full-stack", "full stack", "backend",
    "front-end", "frontend", "front end", "devops", "sre", "data",
    "product", "qa", "quality", "security", "mobile", "ios", "android",
)

COMMON_TITLES = (
    "software engineer", "backend engineer", "frontend engineer",
    "full stack engineer", "full-stack engineer", "python developer",
    "java developer", "data engineer", "data scientist", "ml engineer",
    "machine learning engineer", "devops engineer", "sre",
    "site reliability engineer", "platform engineer", "cloud engineer",
    "security engineer", "qa engineer", "product manager",
    "engineering manager", "tech lead", "technical lead",
    "staff engineer", "principal engineer", "mobile developer",
    "ios developer", "android developer", "web developer",
    "software developer", "backend developer", "frontend developer",
    "ai engineer", "nlp engineer", "research engineer",
)
